### ISSUE TITLE
is this normal , 

### ISSUE THREAD

**Issue by huanggou666** [ShmuelRonen/ComfyUI-ImageMotionGuider#3]
spend a lot of time on  vae encoding,  on RTX4090
![image](https://github.com/user-attachments/assets/d51a9583-49a4-47ce-a057-931a9108a0c6)

![image](https://github.com/user-attachments/assets/7391e73a-b7f3-48c5-95c9-be99040c8315)

**Comment by ShmuelRonen** [comment]
It's related to the size of your image. and the frame_num amount.

**Comment by huanggou666** [comment]
> It's related to the size of your image. and the frame_num amount.

thanks ,I tried with tile encode node, much faster
